### ISSUE TITLE
Derivation path is always using mainnet

### ISSUE THREAD

**Issue by ottosch** [setavenger/blindbitd#12]
keys.go is always using the mainnet path:

```
// m/352'/0'
coinType, err := purpose.Derive(0 + hdkeychain.HardenedKeyStart)
if err != nil {
	logging.ErrorLogger.Println(err)
	return nil, err
}
```

According to [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#user-content-Reference), test networks should use coinType 1.

Should probably use `ChainParams.HDCoinType`, but don't know if there are side-effects (also note `KeysFromMnemonic` is using fixed `&chaincfg.MainNetParams` arg).

**Comment by setavenger** [comment]
that's a good point. I think a simple check for the current chain and just changing the path from 0 to 1 if needed will suffice.
